version: "2"

services:
  just-another-tetris:
    build: .
    image: "just-another-tetris:0.0.1"
    container_name: "just-another-tetris"
    hostname: "just-another-tetris"
    environment:
      - SERVICE_NAME=just-another-tetris
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
