version: "2"

services:
  react-training:
    build: .
    image: "react/training:v1"
    container_name: "react-training"
    hostname: "react-training"
    environment:
      - SERVICE_NAME=react-training
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - .:/usr/src/app
#    command: "tail -f /dev/null"
#    command: "npm install"
#    command: "npm run build:dev"
    expose:
      - "8080"
    ports:
      - "8080:8080"
